### ISSUE TITLE
How to change the output channels?

### ISSUE THREAD

**Issue by luanyunteng** [seungwonpark/RandWireNN#11]
https://github.com/seungwonpark/RandWireNN/blob/6bea89c423fe7c0d46b37f4256953e905986c84c/model/dag_layer.py#L39
hi, @seungwonpark :
When I read your code, I find that you change(i.e., explode) the output channels in the output node instead of the input node. And I review Kaiming He's paper again, there is an explanation "The channel count in a random graph is increased by 2× when going from one stage to the next stage, following [11]", [11] refers to the Residual Network. So I think we should increase the output channels in the input node. How do you think?

**Comment by seungwonpark** [comment]
Hi, @luanyunteng 
Thanks for pointing this out. I thought that the channel count should be increased at output nodes, but I find it unclear this time. (Since I wrote this code a month ago, I can't remember all the details.)
I'll check this again and reply to this thread. Thanks again, and feel free to add more comments here.

**Comment by seungwonpark** [comment]
Top-1 accuracy reached only about 64.0% with this configuration when trained for 250 epochs with CosineAnnealingLR with SGD.
I suspect this issue to be a reason for low accuracy, hence I will try changing this.

**Comment by seungwonpark** [comment]
working on branch `fix/11`. training in progress.

**Comment by seungwonpark** [comment]
I think you're right. I fixed the number of channels and reached 69.2% top1 accuracy, which is far better than 64.0%.
This was fixed and merged to master branch. Thank you!
