### ISSUE TITLE
RandWireNN as backbone of Faster RCNN

### ISSUE THREAD

**Issue by xiaozhuka** [seungwonpark/RandWireNN#9]
Hi @seungwonpark Thanks for you work.

Have you realized the faster rcnn + FPN detection training of RandWireNN as backbone?

**Comment by seungwonpark** [comment]
Hi, @xiaozhuka 
I'm not sure what you're talking about. Could you elaborate more on that, please? Thanks in advance.

**Comment by xiaozhuka** [comment]
Hi @seungwonpark , At the end of the RandWireNN paper, faster rcnn + FPN + RandWireNN is used for detection.

COCO object detection. Finally, we report the transferability results by fine-tuning the networks for COCO object detection [25]. We use Faster R-CNN [35] with FPN [24] as the object detector. Our fine-tuning is based on 1× setting of the publicly available Detectron [9]. We simply replace the backbones with those in Table 3 (regular regime).
![image](https://user-images.githubusercontent.com/6336709/57187464-c454b380-6f21-11e9-9419-ece535e8dae2.png)

**Comment by seungwonpark** [comment]
Oh, yes - I’m already aware of that section, but thanks for pointing it out.

One of the future plans for this repo is to complete the rest part of the paper. However, I thought it would be better to pre-release this repo since:
 1. it’ll benefit researchers who are planning to test the RandWireNN as a backbone for other tasks using ResNet
2. honestly, I do not know well about topics in CV yet. So it’ll take much time to test RandWireNN with Faster R-CNN for me.

Again, thanks for your concern about this. Will this be an answer for your question?

**Comment by xiaozhuka** [comment]
Yes, thanks for your excellent work. I will focus on RandWireNN+FasterRCNN.
